/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author princ
 */
public class DisplayAll extends javax.swing.JFrame {

    /**
     * Creates new form DisplayAll
     */
    public DisplayAll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayAllPanel = new javax.swing.JPanel();
        BackstoMainBtn = new javax.swing.JButton();
        DisplayScrollPane = new javax.swing.JScrollPane();
        InvoiceTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackstoMainBtn.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        BackstoMainBtn.setText("< Main Menu");
        BackstoMainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackstoMainBtnActionPerformed(evt);
            }
        });

        InvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice No.", "Date", "Customer Info.", "Item Description", "Price", "Payments", "Balance", "Memo", "Notes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InvoiceTable.getTableHeader().setReorderingAllowed(false);
        DisplayScrollPane.setViewportView(InvoiceTable);
        if (InvoiceTable.getColumnModel().getColumnCount() > 0) {
            InvoiceTable.getColumnModel().getColumn(0).setResizable(false);
            InvoiceTable.getColumnModel().getColumn(1).setResizable(false);
            InvoiceTable.getColumnModel().getColumn(2).setResizable(false);
            InvoiceTable.getColumnModel().getColumn(3).setResizable(false);
            InvoiceTable.getColumnModel().getColumn(4).setResizable(false);
            InvoiceTable.getColumnModel().getColumn(5).setResizable(false);
            InvoiceTable.getColumnModel().getColumn(6).setResizable(false);
            InvoiceTable.getColumnModel().getColumn(6).setCellEditor(null);
            InvoiceTable.getColumnModel().getColumn(7).setResizable(false);
            InvoiceTable.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout DisplayAllPanelLayout = new javax.swing.GroupLayout(DisplayAllPanel);
        DisplayAllPanel.setLayout(DisplayAllPanelLayout);
        DisplayAllPanelLayout.setHorizontalGroup(
            DisplayAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayAllPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DisplayAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayAllPanelLayout.createSequentialGroup()
                        .addComponent(BackstoMainBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(DisplayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE))
                .addContainerGap())
        );
        DisplayAllPanelLayout.setVerticalGroup(
            DisplayAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayAllPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackstoMainBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayAllPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayAllPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackstoMainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackstoMainBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackstoMainBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackstoMainBtn;
    private javax.swing.JPanel DisplayAllPanel;
    private javax.swing.JScrollPane DisplayScrollPane;
    private javax.swing.JTable InvoiceTable;
    // End of variables declaration//GEN-END:variables
}
