/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author princ
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayAllPanel4 = new javax.swing.JPanel();
        BackstoMainBtn4 = new javax.swing.JButton();
        TitleInvoice = new javax.swing.JLabel();
        TitleDate = new javax.swing.JLabel();
        TitleCustomerInfo = new javax.swing.JLabel();
        TitleItemDescription = new javax.swing.JLabel();
        TitlePrice = new javax.swing.JLabel();
        TitlePayment = new javax.swing.JLabel();
        TitleBalance = new javax.swing.JLabel();
        TitleMemo = new javax.swing.JLabel();
        TitleNote = new javax.swing.JLabel();
        DisplayScrollPane = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackstoMainBtn4.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        BackstoMainBtn4.setText("< Main Menu");
        BackstoMainBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackstoMainBtn4ActionPerformed(evt);
            }
        });

        TitleInvoice.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleInvoice.setText("Invoice");
        TitleInvoice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleDate.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleDate.setText("Date");
        TitleDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleCustomerInfo.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleCustomerInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleCustomerInfo.setText("Customer Info.");
        TitleCustomerInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleCustomerInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleItemDescription.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleItemDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleItemDescription.setText("Item Description");
        TitleItemDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleItemDescription.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitlePrice.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitlePrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitlePrice.setText("Price");
        TitlePrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitlePrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitlePayment.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitlePayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitlePayment.setText("Payment");
        TitlePayment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitlePayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleBalance.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleBalance.setText("Balance");
        TitleBalance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleBalance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleMemo.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleMemo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleMemo.setText("Memo");
        TitleMemo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleMemo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleNote.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleNote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleNote.setText("Notes");
        TitleNote.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleNote.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DisplayScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        DisplayScrollPane.setPreferredSize(new java.awt.Dimension(1571, 737));

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice", "Date", "Customer Info", "Item Description", "Price", "Payments", "Balance", "Memo", "Notes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DisplayTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        DisplayTable.setRowHeight(50);
        DisplayTable.getTableHeader().setResizingAllowed(false);
        DisplayTable.getTableHeader().setReorderingAllowed(false);
        DisplayScrollPane.setViewportView(DisplayTable);
        if (DisplayTable.getColumnModel().getColumnCount() > 0) {
            DisplayTable.getColumnModel().getColumn(0).setResizable(false);
            DisplayTable.getColumnModel().getColumn(0).setPreferredWidth(80);
            DisplayTable.getColumnModel().getColumn(1).setResizable(false);
            DisplayTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            DisplayTable.getColumnModel().getColumn(2).setResizable(false);
            DisplayTable.getColumnModel().getColumn(2).setPreferredWidth(260);
            DisplayTable.getColumnModel().getColumn(3).setResizable(false);
            DisplayTable.getColumnModel().getColumn(3).setPreferredWidth(260);
            DisplayTable.getColumnModel().getColumn(4).setResizable(false);
            DisplayTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            DisplayTable.getColumnModel().getColumn(5).setResizable(false);
            DisplayTable.getColumnModel().getColumn(5).setPreferredWidth(100);
            DisplayTable.getColumnModel().getColumn(6).setResizable(false);
            DisplayTable.getColumnModel().getColumn(6).setPreferredWidth(100);
            DisplayTable.getColumnModel().getColumn(7).setResizable(false);
            DisplayTable.getColumnModel().getColumn(7).setPreferredWidth(250);
            DisplayTable.getColumnModel().getColumn(8).setResizable(false);
            DisplayTable.getColumnModel().getColumn(8).setPreferredWidth(250);
        }

        javax.swing.GroupLayout DisplayAllPanel4Layout = new javax.swing.GroupLayout(DisplayAllPanel4);
        DisplayAllPanel4.setLayout(DisplayAllPanel4Layout);
        DisplayAllPanel4Layout.setHorizontalGroup(
            DisplayAllPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayAllPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DisplayAllPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DisplayAllPanel4Layout.createSequentialGroup()
                        .addGroup(DisplayAllPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackstoMainBtn4)
                            .addGroup(DisplayAllPanel4Layout.createSequentialGroup()
                                .addComponent(TitleInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TitleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TitleItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(TitlePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TitlePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(TitleMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleNote, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DisplayAllPanel4Layout.setVerticalGroup(
            DisplayAllPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayAllPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackstoMainBtn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DisplayAllPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleInvoice)
                    .addComponent(TitleDate)
                    .addComponent(TitleCustomerInfo)
                    .addComponent(TitleItemDescription)
                    .addComponent(TitlePrice)
                    .addComponent(TitlePayment)
                    .addComponent(TitleBalance)
                    .addComponent(TitleMemo)
                    .addComponent(TitleNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayAllPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayAllPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackstoMainBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackstoMainBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackstoMainBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackstoMainBtn4;
    private javax.swing.JPanel DisplayAllPanel4;
    private javax.swing.JScrollPane DisplayScrollPane;
    private javax.swing.JTable DisplayTable;
    private javax.swing.JLabel TitleBalance;
    private javax.swing.JLabel TitleCustomerInfo;
    private javax.swing.JLabel TitleDate;
    private javax.swing.JLabel TitleInvoice;
    private javax.swing.JLabel TitleItemDescription;
    private javax.swing.JLabel TitleMemo;
    private javax.swing.JLabel TitleNote;
    private javax.swing.JLabel TitlePayment;
    private javax.swing.JLabel TitlePrice;
    // End of variables declaration//GEN-END:variables
}
