/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author princ
 */
public class testprint extends javax.swing.JFrame {

    /**
     * Creates new form testprint
     */
    public testprint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrintDisplayTopPanel = new javax.swing.JPanel();
        BacktoDisplayAll = new javax.swing.JButton();
        PrintBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        ReceivePaymentBtn = new javax.swing.JButton();
        PrintScrollPane = new javax.swing.JScrollPane();
        PrintDisplayPanel = new javax.swing.JPanel();
        SuwalLogoLabel = new javax.swing.JLabel();
        SuwalInfoLabel = new javax.swing.JLabel();
        SetOwnerLabel = new javax.swing.JLabel();
        PCustomerInfoLabel = new javax.swing.JLabel();
        PDateLabel = new javax.swing.JLabel();
        PDate = new javax.swing.JLabel();
        PInvoice = new javax.swing.JLabel();
        PInvoiceLabel = new javax.swing.JLabel();
        HLine = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        HLine2 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        GuaranteeLabel = new javax.swing.JLabel();
        BottomLeftLabel = new javax.swing.JLabel();
        BottomRightLabel = new javax.swing.JLabel();
        PMemo = new javax.swing.JLabel();
        TaxLabel = new javax.swing.JLabel();
        BalanceLabel = new javax.swing.JLabel();
        PaymentLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        TaxAmount = new javax.swing.JLabel();
        TotalAmount = new javax.swing.JLabel();
        PaymentAmount = new javax.swing.JLabel();
        BalanceAmount = new javax.swing.JLabel();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BacktoDisplayAll.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        BacktoDisplayAll.setText("<Back");
        BacktoDisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoDisplayAllActionPerformed(evt);
            }
        });

        PrintBtn.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        PrintBtn.setText("Print");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });

        EditBtn.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        ReceivePaymentBtn.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        ReceivePaymentBtn.setText("Receive Payments");
        ReceivePaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceivePaymentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrintDisplayTopPanelLayout = new javax.swing.GroupLayout(PrintDisplayTopPanel);
        PrintDisplayTopPanel.setLayout(PrintDisplayTopPanelLayout);
        PrintDisplayTopPanelLayout.setHorizontalGroup(
            PrintDisplayTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintDisplayTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BacktoDisplayAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReceivePaymentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PrintBtn)
                .addContainerGap())
        );
        PrintDisplayTopPanelLayout.setVerticalGroup(
            PrintDisplayTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintDisplayTopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PrintDisplayTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BacktoDisplayAll)
                    .addComponent(PrintBtn)
                    .addComponent(EditBtn)
                    .addComponent(ReceivePaymentBtn)))
        );

        SuwalLogoLabel.setText("Suwal Logo");

        SuwalInfoLabel.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        SuwalInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SuwalInfoLabel.setText("<html><center>47-12 Junction Blvd. Corona, NY 11368<br>Tel- 718-606-6700   Tel- 718-505-2013<br>www.suwal.net<br>Lic No.-1401112/2001080</center></html>");

        SetOwnerLabel.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        SetOwnerLabel.setText("SET OWNER");
        SetOwnerLabel.setToolTipText("");
        SetOwnerLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        SetOwnerLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        PCustomerInfoLabel.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        PCustomerInfoLabel.setText("<html>PRINCE SUWAL<br>92-01 LAMONT AVE. ELMHURST, NY, 11373<br>(917)-328-9999</html>");

        PDateLabel.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        PDateLabel.setText("DATE:");

        PDate.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        PDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PDate.setText("07/24/2017");

        PInvoice.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        PInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PInvoice.setText("17001");

        PInvoiceLabel.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        PInvoiceLabel.setText("INVOICE NO.");

        HLine.setBackground(new java.awt.Color(0, 0, 0));
        HLine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        HLine2.setBackground(new java.awt.Color(0, 0, 0));
        HLine2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        GuaranteeLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        GuaranteeLabel.setText("<HTML><b>GUARANTEE:</b> 1. All works performed by qualified technicians. 2. All materials used in repair of your unit are of first quality and guaranteed for a period of 30 days after the date of repair. 3. The guarantee only applies for the same problem that the unit was repaired for.<br><b>CUSTOMER CLAIM:</b> 1. This invoice must be presented to redeem your unit. 2. We are not responsible for units undeliverable after 30 days. 3. Your unit may be sold to cover the repair costs.<br><b>RETURN POLICY:</b> EXCHANGE ONLY: Items may be <b> EXCHANGED</b> for other merchandise within 7 days of purchase. <b>NO CASH REFUND, THANK YOU</b></HTML> ");

        BottomLeftLabel.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        BottomLeftLabel.setText("Set Checked and Picked By...................................................");

        BottomRightLabel.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        BottomRightLabel.setText("We Appreciate Your Business!");

        PMemo.setText("Memo for the invoice person item anything");

        TaxLabel.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        TaxLabel.setText("TAX:");
        TaxLabel.setIconTextGap(0);

        BalanceLabel.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        BalanceLabel.setText("BALANCE:");

        PaymentLabel.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        PaymentLabel.setText("PAYMENT:");

        TotalLabel.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        TotalLabel.setText("TOTAL:");
        TotalLabel.setIconTextGap(0);

        TaxAmount.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        TaxAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TaxAmount.setText("$ 190.00");

        TotalAmount.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        TotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalAmount.setText("$ 190.00");

        PaymentAmount.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        PaymentAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PaymentAmount.setText("$ 190.00");

        BalanceAmount.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        BalanceAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BalanceAmount.setText("$ 190.00");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        javax.swing.GroupLayout PrintDisplayPanelLayout = new javax.swing.GroupLayout(PrintDisplayPanel);
        PrintDisplayPanel.setLayout(PrintDisplayPanelLayout);
        PrintDisplayPanelLayout.setHorizontalGroup(
            PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HLine2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GuaranteeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(PrintDisplayPanelLayout.createSequentialGroup()
                        .addComponent(BottomLeftLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BottomRightLabel))
                    .addGroup(PrintDisplayPanelLayout.createSequentialGroup()
                        .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SetOwnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PCustomerInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PrintDisplayPanelLayout.createSequentialGroup()
                                    .addComponent(PDateLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SuwalInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrintDisplayPanelLayout.createSequentialGroup()
                                .addComponent(PInvoiceLabel)
                                .addGap(18, 18, 18)
                                .addComponent(PInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SuwalLogoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(PrintDisplayPanelLayout.createSequentialGroup()
                        .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PrintDisplayPanelLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TaxLabel)
                                    .addComponent(BalanceLabel)
                                    .addComponent(PaymentLabel)
                                    .addComponent(TotalLabel)
                                    .addComponent(PMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TaxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BalanceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PrintDisplayPanelLayout.setVerticalGroup(
            PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintDisplayPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SetOwnerLabel)
                    .addComponent(SuwalLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PCustomerInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuwalInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PDateLabel)
                    .addComponent(PDate)
                    .addComponent(PInvoiceLabel)
                    .addComponent(PInvoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HLine, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 448, Short.MAX_VALUE)
                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalanceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuaranteeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrintDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BottomLeftLabel)
                    .addComponent(BottomRightLabel))
                .addContainerGap())
        );

        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(85);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(600);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
        }

        PrintScrollPane.setViewportView(PrintDisplayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrintDisplayTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PrintScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PrintDisplayTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrintScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BacktoDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoDisplayAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BacktoDisplayAllActionPerformed

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBtnActionPerformed

    private void ReceivePaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceivePaymentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceivePaymentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testprint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoDisplayAll;
    private javax.swing.JLabel BalanceAmount;
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JLabel BottomLeftLabel;
    private javax.swing.JLabel BottomRightLabel;
    private javax.swing.JButton EditBtn;
    private javax.swing.JLabel GuaranteeLabel;
    private javax.swing.Box.Filler HLine;
    private javax.swing.Box.Filler HLine2;
    private javax.swing.JLabel PCustomerInfoLabel;
    private javax.swing.JLabel PDate;
    private javax.swing.JLabel PDateLabel;
    private javax.swing.JLabel PInvoice;
    private javax.swing.JLabel PInvoiceLabel;
    private javax.swing.JLabel PMemo;
    private javax.swing.JLabel PaymentAmount;
    private javax.swing.JLabel PaymentLabel;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JPanel PrintDisplayPanel;
    private javax.swing.JPanel PrintDisplayTopPanel;
    private javax.swing.JScrollPane PrintScrollPane;
    private javax.swing.JButton ReceivePaymentBtn;
    private javax.swing.JLabel SetOwnerLabel;
    private javax.swing.JLabel SuwalInfoLabel;
    private javax.swing.JLabel SuwalLogoLabel;
    private javax.swing.JLabel TaxAmount;
    private javax.swing.JLabel TaxLabel;
    private javax.swing.JLabel TotalAmount;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
