/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoice;

/**
 *
 * @author princ
 */
public class DisplayAll extends javax.swing.JFrame {

    /**
     * Creates new form DisplayAll
     */
    public DisplayAll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayAllPanel = new javax.swing.JPanel();
        BackstoMainBtn = new javax.swing.JButton();
        TitleInvoice = new javax.swing.JLabel();
        TitleDate = new javax.swing.JLabel();
        TitleCustomerInfo = new javax.swing.JLabel();
        TitleItemDescription = new javax.swing.JLabel();
        TitlePrice = new javax.swing.JLabel();
        TitlePayment = new javax.swing.JLabel();
        TitleBalance = new javax.swing.JLabel();
        TitleMemo = new javax.swing.JLabel();
        TitleNote = new javax.swing.JLabel();
        DisplayScrollPane = new javax.swing.JScrollPane();
        ScrollablePanel = new javax.swing.JPanel();
        DInvoice = new javax.swing.JButton();
        DDate = new javax.swing.JLabel();
        DPrice = new javax.swing.JLabel();
        DPayment = new javax.swing.JLabel();
        DBalance = new javax.swing.JLabel();
        DCustomerInfo = new javax.swing.JLabel();
        DItemDescription = new javax.swing.JLabel();
        DMemo = new javax.swing.JLabel();
        DNotes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackstoMainBtn.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        BackstoMainBtn.setText("< Main Menu");
        BackstoMainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackstoMainBtnActionPerformed(evt);
            }
        });

        TitleInvoice.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleInvoice.setText("Invoice");
        TitleInvoice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleDate.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleDate.setText("Date");
        TitleDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleCustomerInfo.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleCustomerInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleCustomerInfo.setText("Customer Info.");
        TitleCustomerInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleCustomerInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleItemDescription.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleItemDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleItemDescription.setText("Item Description");
        TitleItemDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleItemDescription.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitlePrice.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitlePrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitlePrice.setText("Price");
        TitlePrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitlePrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitlePayment.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitlePayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitlePayment.setText("Payment");
        TitlePayment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitlePayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleBalance.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleBalance.setText("Balance");
        TitleBalance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleBalance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleMemo.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleMemo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleMemo.setText("Memo");
        TitleMemo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleMemo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TitleNote.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        TitleNote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleNote.setText("Notes");
        TitleNote.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TitleNote.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DisplayScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        DisplayScrollPane.setPreferredSize(new java.awt.Dimension(1571, 737));

        ScrollablePanel.setBackground(java.awt.SystemColor.activeCaption);
        ScrollablePanel.setPreferredSize(new java.awt.Dimension(1569, 50));
        ScrollablePanel.setVerifyInputWhenFocusTarget(false);

        DInvoice.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        DInvoice.setText("17000");
        DInvoice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DInvoiceActionPerformed(evt);
            }
        });

        DDate.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        DDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DDate.setText("07/21/2017");
        DDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DPrice.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        DPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DPrice.setText("$120.00");
        DPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DPayment.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        DPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DPayment.setText("$120.00");
        DPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DBalance.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        DBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DBalance.setText("$00.00");
        DBalance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DCustomerInfo.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        DCustomerInfo.setText("<html>SUWAL ELECTRONICS<BR>(718)-606-6700</HTML>");
        DCustomerInfo.setToolTipText("");
        DCustomerInfo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        DItemDescription.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        DItemDescription.setText("<html>DELL PC DC7000<BR>OS CRASHED WINDOWS 10</HTML>");
        DItemDescription.setToolTipText("");
        DItemDescription.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        DMemo.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        DMemo.setText("<html>REINSTALL WINDOWS 10 AND MS OFFICE PRO</HTML>");
        DMemo.setToolTipText("");
        DMemo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        DNotes.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        DNotes.setText("<html>BACKUP PICTURES AND MUSIC</HTML>");
        DNotes.setToolTipText("");
        DNotes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout ScrollablePanelLayout = new javax.swing.GroupLayout(ScrollablePanel);
        ScrollablePanel.setLayout(ScrollablePanelLayout);
        ScrollablePanelLayout.setHorizontalGroup(
            ScrollablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollablePanelLayout.createSequentialGroup()
                .addComponent(DInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(DPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ScrollablePanelLayout.setVerticalGroup(
            ScrollablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollablePanelLayout.createSequentialGroup()
                .addGroup(ScrollablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScrollablePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(ScrollablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ScrollablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ScrollablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ScrollablePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ScrollablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(674, 674, 674))
        );

        DCustomerInfo.getAccessibleContext().setAccessibleName("<html>SUWAL ELECTRONICS<BR>(718)-606-6700</HTML>");

        DisplayScrollPane.setViewportView(ScrollablePanel);

        javax.swing.GroupLayout DisplayAllPanelLayout = new javax.swing.GroupLayout(DisplayAllPanel);
        DisplayAllPanel.setLayout(DisplayAllPanelLayout);
        DisplayAllPanelLayout.setHorizontalGroup(
            DisplayAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayAllPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DisplayAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DisplayAllPanelLayout.createSequentialGroup()
                        .addGroup(DisplayAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackstoMainBtn)
                            .addGroup(DisplayAllPanelLayout.createSequentialGroup()
                                .addComponent(TitleInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitlePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitlePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleNote, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DisplayAllPanelLayout.setVerticalGroup(
            DisplayAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayAllPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackstoMainBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DisplayAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleInvoice)
                    .addComponent(TitleDate)
                    .addComponent(TitleCustomerInfo)
                    .addComponent(TitleItemDescription)
                    .addComponent(TitlePrice)
                    .addComponent(TitlePayment)
                    .addComponent(TitleBalance)
                    .addComponent(TitleMemo)
                    .addComponent(TitleNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DisplayAllPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayAllPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackstoMainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackstoMainBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackstoMainBtnActionPerformed

    private void DInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackstoMainBtn;
    private javax.swing.JLabel DBalance;
    private javax.swing.JLabel DCustomerInfo;
    private javax.swing.JLabel DDate;
    private javax.swing.JButton DInvoice;
    private javax.swing.JLabel DItemDescription;
    private javax.swing.JLabel DMemo;
    private javax.swing.JLabel DNotes;
    private javax.swing.JLabel DPayment;
    private javax.swing.JLabel DPrice;
    private javax.swing.JPanel DisplayAllPanel;
    private javax.swing.JScrollPane DisplayScrollPane;
    private javax.swing.JPanel ScrollablePanel;
    private javax.swing.JLabel TitleBalance;
    private javax.swing.JLabel TitleCustomerInfo;
    private javax.swing.JLabel TitleDate;
    private javax.swing.JLabel TitleInvoice;
    private javax.swing.JLabel TitleItemDescription;
    private javax.swing.JLabel TitleMemo;
    private javax.swing.JLabel TitleNote;
    private javax.swing.JLabel TitlePayment;
    private javax.swing.JLabel TitlePrice;
    // End of variables declaration//GEN-END:variables
}
